name = "yehyun-portfolio-api"
main = "src/index.js"
compatibility_date = "2026-08-12"

[vars]
FIREBASE_PROJECT_ID = "yehyun-portfolio"
ALLOWED_ORIGIN = "https://hwahyo-o.github.io"
FRONTEND_URL = "https://hwahyo-o.github.io/yehyun_portfolio"
GOOGLE_REDIRECT_URI = "https://yehyun-portfolio-api.ajas03974.workers.dev/oauth/google/callback"

[[d1_databases]]
binding = "DB"
database_name = "yehyun-portfolio"
database_id = "3a72f8d7-cf47-4afc-8b05-1773c67a0b7e"
